export const Fonts = () => {
  return (
    <>
      <link
        rel="preload"
        as="font"
        type="font/woff"
        href="/fonts/MercuryTextG2-Roman.woff"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff"
        href="/fonts/IdealSans-Black.woff"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff"
        href="/fonts/IdealSans-Medium.woff"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff"
        href="/fonts/IdealSans-Light.woff"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff"
        href="/fonts/IdealSans-Thin.woff"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff2"
        href="/fonts/MercuryTextG2-Roman.woff2"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff2"
        href="/fonts/IdealSans-Black.woff2"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff2"
        href="/fonts/IdealSans-Medium.woff2"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff2"
        href="/fonts/IdealSans-Light.woff2"
        crossOrigin=""
      />
      <link
        rel="preload"
        as="font"
        type="font/woff2"
        href="/fonts/IdealSans-Thin.woff2"
        crossOrigin=""
      />
    </>
  );
};
