import type { NextPage, GetServerSidePropsContext } from "next";
import Head from "next/head";
import { MainPage } from "../src/components/Main";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Insomniac task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
    </div>
  );
};

export default Home;
